using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Ironwall.Libraries.Enums
{
    public enum EnumCmdType
    {
        HEART_BEAT_REQUEST,
        HEART_BEAT_RESPONSE,

        LOGIN_REQUEST,
        LOGIN_REQUEST_FORCE,
        LOGIN_RESPONSE,

        LOGOUT_REQUEST,
        LOGOUT_REQUEST_FORCE_LOGIN,
        LOGOUT_REQUEST_TIMEOUT,
        LOGOUT_RESPONSE,

        SESSION_REFRESH_REQUEST,
        SESSION_REFRESH_RESPONSE,

        USER_ACCOUNT_ADD_REQUEST,
        USER_ACCOUNT_ADD_RESPONSE,
        USER_ACCOUNT_ID_CHECK_REQUEST,
        USER_ACCOUNT_ID_CHECK_RESPONSE,
        USER_ACCOUNT_EDIT_REQUEST,
        USER_ACCOUNT_EDIT_RESPONSE,
        USER_ACCOUNT_DELETE_REQUEST,
        USER_ACCOUNT_DELETE_RESPONSE,

        USER_ACCOUNT_INFO_REQUEST,
        USER_ACCOUNT_INFO_RESPONSE,

        USER_ACCOUNT_ALL_REQUEST,
        USER_ACCOUNT_ALL_RESPONSE,

        USER_ACCOUNT_ALL_DELETE_REQUEST,
        USER_ACCOUNT_ALL_DELETE_RESPONSE,

        EVENT_CONNECTION_REQUEST,
        EVENT_CONNECTION_RESPONSE,

        EVENT_DETECTION_REQUEST,
        EVENT_DETECTION_RESPONSE,

        EVENT_MALFUNCTION_REQUEST,
        EVENT_MALFUNCTION_RESPONSE,
        
        EVENT_CONTACT_ON_REQUEST,
        EVENT_CONTACT_ON_RESPONSE,

        EVENT_CONTACT_OFF_REQUEST,
        EVENT_CONTACT_OFF_RESPONSE,

        EVENT_ACTION_REQUEST,
        EVENT_ACTION_RESPONSE,

        EVENT_ACTION_DETECTION_REQUEST,
        EVENT_ACTION_DETECTION_RESPONSE,

        EVENT_ACTION_MALFUNCTION_REQUEST,
        EVENT_ACTION_MALFUNCTION_RESPONSE,

        SEARCH_EVENT_CONNECTION_REQUEST,
        SEARCH_EVENT_CONNECTION_RESPONSE,

        SEARCH_EVENT_DETECTION_REQUEST,
        SEARCH_EVENT_DETECTION_RESPONSE,

        SEARCH_EVENT_MALFUNCTION_REQUEST,
        SEARCH_EVENT_MALFUNCTION_RESPONSE,

        SEARCH_EVENT_ACTION_REQUEST,
        SEARCH_EVENT_ACTION_RESPONSE,

        DEVICE_MAX_ID_REQUEST,
        DEVICE_MAX_ID_RESPONSE,

        DEVICE_DATA_REQUEST,
        DEVICE_DATA_RESPONSE,

        CONTROLLER_DATA_REQUEST,
        CONTROLLER_DATA_RESPONSE,

        CONTROLLER_DATA_SAVE_REQUEST,
        CONTROLLER_DATA_SAVE_RESPONSE,

        SENSOR_DATA_REQUEST,
        SENSOR_DATA_RESPONSE,

        SENSOR_DATA_SAVE_REQUEST,
        SENSOR_DATA_SAVE_RESPONSE,

        CAMERA_DATA_REQUEST,
        CAMERA_DATA_RESPONSE,

        CAMERA_DATA_SAVE_REQUEST,
        CAMERA_DATA_SAVE_RESPONSE,

        /// <summary>
        /// Camera Option
        /// </summary>
        CAMERA_MAPPING_DATA_REQUEST,
        CAMERA_MAPPING_DATA_RESPONSE,

        CAMERA_MAPPING_SAVE_REQUEST,
        CAMERA_MAPPING_SAVE_RESPONSE,

        CAMERA_OPTION_REQUEST,
        CAMERA_OPTION_RESPONSE,

        CAMERA_PRESET_DATA_REQUEST,
        CAMERA_PRESET_DATA_RESPONSE,

        CAMERA_PRESET_SAVE_REQUEST,
        CAMERA_PRESET_SAVE_RESPONSE,

        SETTING_INFO_REQUEST,
        SETTING_INFO_RESPONSE,

        SYMBOL_DATA_INFO_REQUEST,
        SYMBOL_DATA_INFO_RESPONSE,

        SYMBOL_DATA_LOAD_REQUEST,
        SYMBOL_DATA_LOAD_RESPONSE,

        SYMBOL_DATA_SAVE_REQUEST,
        SYMBOL_DATA_SAVE_RESPONSE,

        SYMBOL_DATA_REQUEST,
        SYMBOL_DATA_RESPONSE,

        SHAPE_SYMBOL_DATA_REQUEST,
        SHAPE_SYMBOL_DATA_RESPONSE,

        OBJECT_SHAPE_DATA_REQUEST,
        OBJECT_SHAPE_DATA_RESPONSE,

        MAP_FILE_LOAD_REQUEST,
        MAP_FILE_LOAD_RESPONSE,
        MAP_FILE_SAVE_REQUEST,
        MAP_FILE_SAVE_RESPONSE,

        MODE_WINDY_REQUEST,
        MODE_WINDY_RESPONSE,

        STATUS_UPDATE,

        /// <summary>
        /// VMS API COMMAND
        /// </summary>
        API_LOGIN_REQUEST,
        API_LOGIN_RESPONSE,

        API_USER_GET_REQUEST,
        API_USER_GET_RESPONSE,

        API_LOGOUT_REQUEST,
        API_LOGOUT_RESPONSE,

        API_KEEP_ALIVE_USER_REQUEST,
        API_KEEP_ALIVE_USER_RESPONSE,

        API_ACT_EVENT_REQUEST,
        API_ACT_EVENT_RESPONSE,

        API_LIST_EVENT_REQUEST,
        API_LIST_EVENT_RESPONSE,

        API_MAPPING_LIST_REQUEST,
        API_MAPPING_LIST_RESPONSE,

        API_MAPPING_SAVE_REQUEST,
        API_MAPPING_SAVE_RESPONSE,
    }
}
